"""create stations and observations tables

Revision ID: 137754888e6e
Revises: 
Create Date: 2026-04-26 23:14:07.767899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137754888e6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('src_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('first_year', sa.Integer(), nullable=False),
    sa.Column('last_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('src_id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('max_air_temp', sa.Float(), nullable=True),
    sa.Column('min_air_temp', sa.Float(), nullable=True),
    sa.Column('prcp_amt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.src_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('stations')
    # ### end Alembic commands ###
