"""create observations table

Revision ID: 1470a0876beb
Revises: 1f63b82b71e0
Create Date: 2026-04-25 12:44:05.193277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1470a0876beb'
down_revision: Union[str, Sequence[str], None] = '1f63b82b71e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('max_air_temp', sa.Float(), nullable=True),
    sa.Column('min_air_temp', sa.Float(), nullable=True),
    sa.Column('prcp_amt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    # ### end Alembic commands ###
