"""create climate_metrics table

Revision ID: e72d235fc2ea
Revises: 137754888e6e
Create Date: 2026-04-29 15:07:53.622265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72d235fc2ea'
down_revision: Union[str, Sequence[str], None] = '137754888e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('avg_max_temp', sa.Float(), nullable=True),
    sa.Column('avg_min_temp', sa.Float(), nullable=True),
    sa.Column('avg_prcp', sa.Float(), nullable=True),
    sa.Column('hot_days', sa.Integer(), nullable=True),
    sa.Column('frost_days', sa.Integer(), nullable=True),
    sa.Column('heavy_rain_days', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.src_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('climate_metrics')
    # ### end Alembic commands ###
